- platform: template
  switches:
    kayee_fan_onoff:
      value_template: '{{ value == "off" }}'
      turn_on:
        service: fan.turn_on
        data:
          entity_id: fan.kayee_fan
      turn_off:
        service: fan.turn_off
        data:
          entity_id: fan.kayee_fan
